blank_issues_enabled: false

contact_links:
  - name: ğŸ“ Ask a Question or Start a Discussion
    url: https://github.com/blokhaus/near-community-blog-proto/discussions
    about: Use Discussions for non-urgent questions, brainstorming, or general ideas

